Repository chtheiss/duskhaven_launcher, pull requests merged in 2023-04, with the labels that each got.

#10 Pull request to fix Linux Support
  README.md
  duskhaven_launcher.py
Labels: bug, documentation

#12 Add the option to save credentials and auto login
  README.md
  credentials.py
  duskhaven_launcher.py
  requirements.txt
  settings.py
Labels: enhancement

#18 Fix pynput AttributeError on quit
  credentials.py
  duskhaven_launcher.py
Labels: bug

#20 Add Server Status Bar
  .pre-commit-config.yaml
  config.py
  duskhaven_launcher.py
  server_status.py
  threads.py
  utils.py
Labels: enhancement
